app:
  image: ibmcom/swift-ubuntu:3.1
  volumes:
    - .:/root/CloudConfiguration
  command: bash -c "cd /root/CloudConfiguration && rm -rf Packages/ && swift package clean && swift build && swift test"
